from typing import Protocol

from src.controller.health.protocols import ReadinessChecking
from src.controller.search.protocols import SupplierSearching
from src.controller.supplier.protocols import SupplierProfiles
from src.controller.upload.protocols import ProcurementUploads


class BackgroundTask(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...


class ServiceProvider(Protocol):
    async def supplier_search(self) -> SupplierSearching: ...

    async def supplier_profiles(self) -> SupplierProfiles: ...

    async def procurement_uploads(self) -> ProcurementUploads: ...

    async def health(self) -> ReadinessChecking: ...

    async def background(self) -> tuple[BackgroundTask, ...]: ...

    async def aclose(self) -> None: ...
