from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.models.upload import LotDetail, UploadDetail, UploadResults, UploadSummary


class ProcurementUploads(Protocol):
    async def start(self) -> None: ...

    async def stop(self) -> None: ...

    async def upload(self, file_name: str, content: bytes) -> UploadSummary: ...

    async def recent(self, limit: int) -> tuple[UploadSummary, ...]: ...

    async def summary(self, upload_id: UUID) -> UploadSummary: ...

    async def get(self, upload_id: UUID) -> UploadDetail: ...

    async def lot(self, upload_id: UUID, lot_id: str) -> LotDetail: ...

    async def results(self, upload_id: UUID, lot_ids: Sequence[str]) -> UploadResults: ...
