COLUMNS = {
    "procurement_lots": (
        "lot_id",
        "procedure_id",
        "reqnum",
        "procedure_name",
        "subject",
        "start_price",
        "is_smp",
        "customer_inn",
        "customer_kpp",
        "platform",
        "version",
        "is_deleted",
        "publish_date",
        "archive_index_id",
        "archive_history_before",
    ),
    "procurement_items": (
        "procurement_item_id",
        "lot_id",
        "source_row_key",
        "product_name",
        "okpd2_code",
        "item_type",
        "requirements",
        "quantity",
        "unit",
        "catalog_item_id",
        "match_status",
        "match_confidence",
        "match_algorithm_version",
        "match_explanation",
        "version",
        "is_deleted",
    ),
    "lot_participations": (
        "lot_id",
        "supplier_inn",
        "supplier_kpp",
        "supplier_id",
        "is_winner",
        "version",
        "is_deleted",
        "winner_label_status",
    ),
}
REGISTRY_COLUMNS = (
    "index_id",
    "history_before",
    "prepared_sha256",
    "lots",
    "items",
    "participations",
    "status",
)
